# Generated by Django 4.1.9 on 2023-07-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="meal",
            fields=[
                ("id_meal", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="meal_type",
            fields=[
                ("id_meal_type", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="user_meal",
            fields=[
                ("id_user_meal", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "id_meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gustos.meal"
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gustos.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="meal",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gustos.meal_type"
            ),
        ),
    ]
